# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: SalesforceAdvancedDay3

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  Deployment:
  
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        deplyHosts: ['34.227.176.180', '23.23.33.230']
    
    steps:
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v4
      with:
        name: buildartifact
        path: target/*.jar

    - name: 'Download Artifact'
      uses: actions/download-artifact@v4
      with:
        name: buildartifact
        path: .
        
    - name: 'Deploy Artifact'
      run: ls -lart
    
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        port: 22
        source: '*.jar'
        target: /tmp/

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        port: 22
        script: | 
          sudo cp /tmp*.jar /opt/
          sudo ls -lart /opt
      
